require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7
RSpec/NestedGroups:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
